"""Generate PostgreSQL DDL from the muse_db schema reference (skills/muse_db/references/schema.md).

The reference lists every table as a markdown table of columns plus a
"Keys and relationships" bullet list. This script parses that into CREATE
SCHEMA / CREATE TABLE statements. Foreign keys are emitted as comments
(soft references in the source), primary keys and unique constraints are real.
"""
from __future__ import annotations
import re, sys, pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / "skills/muse_db/references/schema.md"
OUT = pathlib.Path(__file__).resolve().parent / "schema.sql"

text = SRC.read_text(encoding="utf-8")
tables_start = text.index("\n## Tables")
body = text[tables_start:]

table_re = re.compile(r"^#### `([a-z_]+)\.([a-z_0-9]+)`\s*$", re.M)
matches = list(table_re.finditer(body))
schemas: dict[str, list[str]] = {}
stmts: list[str] = []
n_tables = n_cols = 0

def unq(s: str) -> str:
    return s.strip().strip("`").strip()

for i, m in enumerate(matches):
    schema, table = m.group(1), m.group(2)
    end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
    section = body[m.end():end]
    cols = []
    for line in section.splitlines():
        if not line.startswith("| `"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        name, typ, nullable, default = unq(cells[0]), unq(cells[1]), cells[2].lower(), unq(cells[3])
        col = f'    "{name}" {typ}'
        if nullable.startswith("no"):
            col += " NOT NULL"
        # the markdown source truncates long generated defaults (unbalanced parens, stray backslashes); skip those
        if default and "\\" not in default and default.count("(") == default.count(")"):
            col += f" DEFAULT {default}"
        cols.append(col)
    if not cols:
        continue
    n_tables += 1; n_cols += len(cols)
    schemas.setdefault(schema, [])
    constraints, comments = [], []
    for line in section.splitlines():
        line = line.strip()
        if line.startswith("- PRIMARY KEY"):
            mm = re.match(r"- PRIMARY KEY `([^`]+)`: (.*)", line)
            if mm:
                keys = ", ".join(f'"{unq(k)}"' for k in mm.group(2).split(","))
                constraints.append(f'    CONSTRAINT "{mm.group(1)}" PRIMARY KEY ({keys})')
        elif line.startswith("- UNIQUE"):
            mm = re.match(r"- UNIQUE `([^`]+)`: (.*)", line)
            if mm:
                keys = ", ".join(f'"{unq(k)}"' for k in mm.group(2).split(","))
                constraints.append(f'    CONSTRAINT "{mm.group(1)}" UNIQUE ({keys})')
        elif line.startswith("- FOREIGN KEY") or line.startswith("- INDEX"):
            comments.append("    -- " + line[2:])
    parts = cols + constraints
    ddl = f'CREATE TABLE IF NOT EXISTS "{schema}"."{table}" (\n' + ",\n".join(parts) + "\n);"
    if comments:
        ddl += "\n" + "\n".join(comments)
    stmts.append(ddl)

out = ["-- Generated by db/gen_schema.py from skills/muse_db/references/schema.md",
       "-- Soft references and indexes are preserved as comments.", ""]
out += ["CREATE EXTENSION IF NOT EXISTS vector;", ""]
out += [f'CREATE SCHEMA IF NOT EXISTS "{s}";' for s in sorted(schemas)]
out.append("")
# Custom types the reference uses but never enumerates: keep them as text domains so
# any value the runtime writes is accepted, without guessing Meta's enum members.
all_ddl = "\n".join(stmts)
custom_types = sorted(set(re.findall(r'" ([a-z]+\.[a-z_]+)(?: NOT NULL|,|\n)', all_ddl)))
custom_types = [t for t in custom_types if t.split(".")[0] in schemas and not t.endswith("_seq")]
out += [f'DO $$ BEGIN CREATE DOMAIN {t} AS text; EXCEPTION WHEN duplicate_object THEN NULL; END $$;' for t in custom_types]
sequences = sorted(set(re.findall(r"nextval\('([a-z_.]+)'", all_ddl)))
out += [f"CREATE SEQUENCE IF NOT EXISTS {s};" for s in sequences]
out.append("")
out += stmts
OUT.write_text("\n\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {OUT} : {len(schemas)} schemas, {n_tables} tables, {n_cols} columns")
